ShoeMartMVC/Controllers/HomePageController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeMartMVC.Models;
using ShoeMartMVC.ViewModel;

namespace ShoeMartMVC.Controllers
{
    public class HomePageController : Controller
    {
        HttpClient client;
        HttpResponseMessage response;
        List<Shoe> shoesList = new List<Shoe>();
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            CustomerBusinessLayer bal = new CustomerBusinessLayer();
            Customer cl = new Customer();
            cl.CustomerId = bal.ReturnID();
            cl.CustomerName = bal.getname();
            if (cl.CustomerId == 0)
            {
                return RedirectToAction("Login", "Authentication");
            }
            client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5120/");
            response = client.GetAsync("api/Shoe/GetAllShoes/").Result;
            List<Shoe> ShoeList = (List<Shoe>)response.Content.ReadFromJsonAsync<IEnumerable<Shoe>>().Result;
            ShoeRecords shoerecords = new ShoeRecords();
            shoerecords.shoes = ShoeList;
            shoerecords.CustomerId = cl.CustomerId;
            shoerecords.CustomerName = cl.CustomerName;
            return View(shoerecords);
        }
        public IActionResult AdminHome()
        {
            AdminViewModel adminViewModel = new AdminViewModel();
            AdminBusinessLayer adminBusiness = new AdminBusinessLayer();
            adminViewModel.adminvm = adminBusiness.ReturnAdmin();
            return View(adminViewModel);
        }
    }
}

ShoeMartMVC/Views/Admin/AdminCustomersView.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model AdminViewModel
@{
    ViewBag.Title = "AdminCustomersView";
}
@{
    Layout = null;
}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h2>Hello Admin,@Model.adminvm.AdminName</h2>
    <h4>Select The Customer Functionality You Want to Work With.</h4>
    <div style="margin: auto;
             width: 70%;
             padding: 8px;"
                               }>
        <button type="button" style="margin:12px" class="btn btn-outline-primary" onclick="location.href='@Url.Action("AdminGetAllCustomers", "Admin")'">GetAllCustomers</button>
        <button type="button" style="margin:12px"class="btn btn-outline-success" onclick="location.href='@Url.Action("AdminUpdateCustomers", "Admin")'">UpdateCustomer</button>
        <button type="button" style="margin:12px"class="btn btn-outline-danger" onclick="location.href='@Url.Action("AdminDeleteCustomer", "Admin")'">DeleteCustomer</button>
    </div>
    <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminHome", "HomePage")'">GoBack</button>
          </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminDeleteCustomer.cshtml
@{
    ViewBag.Title = "AdminDeleteCustomer";
} 
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Delete</title>
</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">DeleteCustomer</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/DeleteCustomer/" method="post">
            
            <div class="col-12 mb-3">
            <label for="CustomerId" class="form-label" >CustomerId</label>
            <input type="text"  class="form-control" id="CustomerId" name="CustomerId" required>
            </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Delete</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminCustomersView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminDeleteReview.cshtml
@{
    ViewBag.Title = "AdminDeleteReview";
} 
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Delete</title>
</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">DeleteReview</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/DeleteReview/" method="post">
            
            <div class="col-12 mb-3">
            <label for="ReviewId" class="form-label" >ReviewId</label>
            <input type="text"  class="form-control" id="ReviewId" name="ReviewId" required>
            </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Delete</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminReviewsView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminDeleteShoe.cshtml
@{
    ViewBag.Title = "AdminDeleteShoe";
} 
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Delete</title>
</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">DeleteShoe</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/DeleteShoe/" method="post">
            
            <div class="col-12 mb-3">
            <label for="ShoeId" class="form-label" >ShoeId</label>
            <input type="text"  class="form-control" id="ShoeId" name="ShoeId" required>
            </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Delete</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminShoesView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminGetAllCustomers.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model CustomerRecords
@{
    ViewBag.Title = "AdminGetAllCustomers";
}
@{
    Layout = null;
}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div>
       <table class="table-success">
        @foreach (Customer item in Model.customersCR)
        {
            <tr>
                <td>CustomerId</td>
                <td>CustomerName</td>
                <td>CustomerAge</td>
                <td>CustomerAddress</td>
                <td>CustomerEmail</td>
                <td>CustomerPhoneNumber</td>
            </tr>
            <tr>
                <td>@item.CustomerId</td>
                <td>@item.CustomerName
                </td>
                <td>
                    @item.Age
                </td>
                <td>@item.Address</td>
                <td>@item.EmailId</td>
                <td>@item.PhoneNumber</td>
            </tr>
        }
    </table>
     <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("AdminCustomersView", "Admin")'">GoBack</button>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminGetAllReviews.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model ReviewRecords
@{
    ViewBag.Title = "AdminGetAllReviews";
}
@{
    Layout = null;
}
    
 <html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div>
       <table class="table-success">
        @foreach (Review item in Model.Reviews)
        {
            <tr>
                <td>ReviewId</td>
                <td>CustomerName</td>
                <td>ShoeId</td>
                <td>Rating</td>
                <td>Feedback</td>
                <td>ReviewTime</td>
            </tr>
            <tr>
                <td>@item.ReviewId</td>
                <td>@item.CustomerName
                </td>
                <td>
                    @item.ShoeId
                </td>
                <td>@item.Rating</td>
                <td>@item.Feedback</td>
                <td>@item.ReviewTime</td>
            </tr>
        }
    </table>
     <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("AdminReviewsView", "Admin")'">GoBack</button>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminGetAllShoes.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model ShoeRecords
@{
    ViewBag.Title = "AdminGetAllShoes";
}
@{
    Layout = null;
}
    
 <html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
<div>
       <table class="table-success">
        @foreach (Shoe item in Model.shoes)
        {
            <tr>
                <td>ShoeId</td>
                <td>ShoeImage</td>
                <td>ShoeName</td>
                <td>Brand</td>
                <td>Price</td>
                <td>Size</td>
            </tr>
            <tr>
                <td>@item.ShoeId</td>
                <td><img src="@item.ShoeImage" height="120" width="120">
                </td>
                <td>
                    @item.ShoeName
                </td>
                <td>@item.Brand</td>
                <td>@item.Price</td>
                <td>@item.Size</td>
            </tr>
        }
    </table>
     <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("AdminShoesView", "Admin")'">GoBack</button>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminReviewsView.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model AdminViewModel
@{
    ViewBag.Title = "AdminReviewsView";
}
@{
    Layout = null;
}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h2>Hello Admin,@Model.adminvm.AdminName</h2>
    <h4>Select The Review Functionality You Want to Work With.</h4>
    <div style="margin: auto;
             width: 70%;
             padding: 8px;"
                               }>
        <button type="button" style="margin:12px" class="btn btn-outline-primary" onclick="location.href='@Url.Action("AdminGetAllReviews", "Admin")'">GetAllReviews</button>
        <button type="button" style="margin:12px"class="btn btn-outline-success" onclick="location.href='@Url.Action("AdminUpdateReviews", "Admin")'">UpdateReview</button>
        <button type="button" style="margin:12px"class="btn btn-outline-danger" onclick="location.href='@Url.Action("AdminDeleteReview", "Admin")'">DeleteReview</button>
    </div>
     <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminHome", "HomePage")'">GoBack</button>
     </div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminShoesView.cshtml
@using ShoeMartMVC.ViewModel
@using ShoeMartMVC.Models
@model AdminViewModel
@{
    ViewBag.Title = "AdminShoesView";
}
@{
    Layout = null;
}
<html>
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <h2>Hello Admin,@Model.adminvm.AdminName</h2>
    <h4>Select The Shoe Functionality You Want to Work With.</h4>
    <div style="margin: auto;
             width: 70%;
             padding: 8px;"
                               }>
        <button type="button" style="margin:12px" class="btn btn-outline-primary" onclick="location.href='@Url.Action("AdminGetAllShoes", "Admin")'">GetAllShoes</button>
        <button type="button" style="margin:12px"class="btn btn-outline-success" onclick="location.href='@Url.Action("AdminUpdateShoes", "Admin")'">UpdateShoe</button>
        <button type="button" style="margin:12px"class="btn btn-outline-danger" onclick="location.href='@Url.Action("AdminDeleteShoe", "Admin")'">DeleteShoe</button>
    </div>
     <div class="col-4 mb-3">
       <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminHome", "HomePage")'">GoBack</button>
     </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminUpdateCustomers.cshtml
@{
    ViewBag.Title = "AdminUpdateCustomers";
} 
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Update</title>

</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">UpdateCustomer</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/UpdateCustomer/" method="post">
            
            <div class="col-12 mb-3">
            <label for="CustomerId" class="form-label" >CustomerId</label>
            <input type="text"  class="form-control" id="CustomerId" name="CustomerId" required>
            </div>
             <div class="col-12 mb-3">
            <label for="CustomerName" class="form-label" >CustomerName</label>
            <input type="text"  class="form-control" id="CustomerName" name="CustomerName" required>
            </div>
            <div class="col-12 mb-3">
            <label for="PhoneNumber" class="form-label">PhoneNumber</label>
            <input type="text" class="form-control" id="PhoneNumber" name="PhoneNumber" required>
          </div>
         
            <div class="col-12 mb-3">
            <label for="Age" class="form-label">Age</label>
            <input type="text" class="form-control" id="Age" name="Age" required />
        </div>
           <div class="col-12 mb-3">
            <label for="Address" class="form-label">Address</label>
            <input type="text" class="form-control" id="Address" name="Address" required>
          </div>
           <div class="col-12 mb-3">
            <label for="EmailId" class="form-label">EmailId</label>
            <input type="email" class="form-control" id="EmailId" name="EmailId" required>
          </div>
           <div class="col-12 mb-3">
            <label for="Password" class="form-label">Password</label>
            <input type="password" class="form-control" id="Password" name="Password" required>
          </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Update</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminCustomersView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminUpdateReviews.cshtml
@{
    ViewBag.Title = "AdminUpdateReviews";
} 
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Update</title>

</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">UpdateReview</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/UpdateReview/" method="post">
            <div class="col-12 mb-3">
            <label for="ReviewId" class="form-label" >ReviewId</label>
            <input type="text"  class="form-control" id="ReviewId" name="ReviewId" required>
            </div>
             <div class="col-12 mb-3">
            <label for="CustomerName" class="form-label" >CustomerName</label>
            <input type="text"  class="form-control" id="CustomerName" name="CustomerName" required>
            </div>
            <div class="col-12 mb-3">
            <label for="Feedback" class="form-label">Feedback</label>
            <input type="text" class="form-control" id="Feedback" name="Feedback" required>
          </div>
         
            <div class="col-12 mb-3">
            <label for="Rating" class="form-label">Rating</label>
            <input type="text" class="form-control" id="Rating" name="Rating" required />
        </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Update</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminReviewsView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Admin/AdminUpdateShoes.cshtml
@{
    ViewBag.Title = "AdminUpdateShoes";
} 

@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<link rel="stylesheet" href="style.css">  
<title>Update</title>

</head>
<body>
    <div style="margin: auto;
             width: 60%;
             padding: 8px;
                               }">
    <h2 style="color:gray;">UpdateShoe</h2>
    </div>
     <div style="margin: auto;
             width: 60%;
             border: 2px solid green;
             padding: 8px;
                               }"> 
        <form action="/Admin/UpdateShoe/" method="post">
            <div class="col-12 mb-3">
            <label for="ShoeId" class="form-label" >ShoeId</label>
            <input type="text"  class="form-control" id="ShoeId" name="ShoeId" required>
            </div>
             <div class="col-12 mb-3">
            <label for="ShoeName" class="form-label" >ShoeName</label>
            <input type="text"  class="form-control" id="ShoeName" name="ShoeName" required>
            </div>
            <div class="col-12 mb-3">
            <label for="Price" class="form-label">Price</label>
            <input type="text" class="form-control" id="Price" name="Price" required>
          </div>
         
            <div class="col-12 mb-3">
            <label for="Size" class="form-label">Size</label>
            <input type="text" class="form-control" id="Size" name="Size" required />
        </div>
        <div class="col-12 mb-3">
            <label for="Brand" class="form-label">Brand</label>
            <input type="text" class="form-control" id="Brand" name="Brand" required />
        </div>
        <div class="col-12 mb-3">
            <label for="ShoeImage" class="form-label">ShoeImage</label>
            <input type="text" class="form-control" id="ShoeImage" name="ShoeImage" required />
        </div>
            <div class="col-4 mb-3">
          <button type="submit" class="btn btn-success"value="Submit" id="btnsub">Update</button>
          </div> 
         </form>
         <div class="col-4 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("AdminShoesView", "Admin")'">GoBack</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>