ShoeMartMVC/Controllers/AuthenticationController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeMartMVC.Models;
using ShoeMartMVC.ViewModel;

namespace ShoeMartMVC.Controllers
{
    public class AuthenticationController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }
        
        public ActionResult DoLogin(Customer customer)
        {
            CustomerBusinessLayer bal = new CustomerBusinessLayer();
            Customer c1 = new Customer();
            bool IsValidUser(Customer customer)
            {
                HttpClient client;
                HttpResponseMessage response;
                client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:5120/");
                response = client.GetAsync("api/Customer/GetAllCustomers/").Result;

                var customers = response.Content.ReadFromJsonAsync<IEnumerable<Customer>>().Result;

                foreach (Customer customerc in customers)
                {
                    if ((customerc.EmailId == customer.EmailId) && (customerc.Password == customer.Password))
                    {
                        customer.CustomerId = customerc.CustomerId;
                        
                        bal.user(customerc.CustomerId);
                        bal.setname(customerc.CustomerName);
                        return true;
                    }

                }
                return false;
            }
           
            if (IsValidUser(customer))
            {

                return RedirectToAction("GetAll", "HomePage");
            }
            else
            {

                return View("Login");
            }
        }
        public ActionResult AdminLogin()
        {
            return View();
        }
        public IActionResult AdminDoLogin(Admin admin)
        {
            AdminBusinessLayer adminbusinesslayer = new AdminBusinessLayer();
            bool IsValidAdmin(Admin adminValid)
            {
                HttpClient client;
                HttpResponseMessage response;
                client = new HttpClient();
                client.BaseAddress = new Uri("http://localhost:5120/");
                response = client.GetAsync("api/Admin/GetAllAdmins/").Result;

                var admins = response.Content.ReadFromJsonAsync<IEnumerable<Admin>>().Result;

                foreach (Admin admincheck in admins)
                {
                    if ((admincheck.UserId == adminValid.UserId) && (admincheck.Password == adminValid.Password))
                    {
                        adminbusinesslayer.getAdmin(admincheck);
                        return true;
                    }

                }
                return false;
            }

            if (IsValidAdmin(admin))
            {
                return RedirectToAction("AdminHome", "HomePage");
            }
            else
            {
                return View("AdminLogin");
            }

        }
        public IActionResult Logout()
        {
            CustomerBusinessLayer customerBusiness = new CustomerBusinessLayer();
            customerBusiness.user(0);
            customerBusiness.setname(" ");
            return RedirectToAction("Login","Authentication");
        }
        public IActionResult AdminLogout()
        {
            AdminBusinessLayer adminBusiness = new AdminBusinessLayer();
            Admin admin = new Admin();
            adminBusiness.getAdmin(admin);
            return RedirectToAction("AdminLogin", "Authentication");
        }
    }
}

ShoeMartMVC/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using ShoeMartMVC.Models;

namespace ShoeMartMVC.Controllers
{
    public class RegistrationController : Controller
    {
        HttpClient client;
        HttpResponseMessage response;
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Register(Customer customer)
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:5120/");
            response = client.PostAsJsonAsync("api/Customer/Create/",customer).Result;
            return RedirectToAction("Login", "Authentication");
        }
        public IActionResult RegistrationPage()
        {
            return View();
        }
    }
}

ShoeMartMVC/Views/Authentication/AdminLogin.cshtml
@model ShoeMartMVC.Models.Admin
@{
    ViewBag.Title = "AdminLogin";
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AdminLogin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div style="margin: auto;
             width: 40%;
             padding: 8px;"
                               }">
    <h2 style="color:gray">Admin Login</h2>
    </div>
        <div style="margin: auto;
             width: 40%;
             border: 2px solid green;
             padding: 8px;"
                               }">
        <form action="/Authentication/AdminDoLogin/" method="post">
            
            <div class="col-8 mb-3">
            <label for="UserId" class="form-label" >UserId</label>
            <input type="text" class="form-control" name="UserId">
          </div>
            <div class="col-8 mb-3">
            <label for="Password" class="form-label">Password</label>
            <input type="password" class="form-control" name="Password">
          </div>
            <div class="col-6 mb-3">
          <button type="submit" class="btn btn-success"value="Login">AdminLogin</button>
          </div>
         
         </form>
          <div class="col-6 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Login", "Authentication")'">Back To Customer Login</button>
          </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

ShoeMartMVC/Views/Authentication/Login.cshtml
@model ShoeMartMVC.Models.Customer
@{
    ViewBag.Title = "Login";
}
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div style="margin: auto;
             width: 40%;
             padding: 8px;"
                               }">
    <h2 style="color:gray">Customer Login</h2>
    </div>
        <div style="margin: auto;
             width: 40%;
             border: 2px solid green;
             padding: 8px;"
                               }">
        <form action="/Authentication/DoLogin/" method="post">
            
            <div class="col-8 mb-3">
            <label for="EmailId" class="form-label" >EmailId</label>
            <input type="email" class="form-control" name="EmailId">
          </div>
            <div class="col-8 mb-3">
            <label for="Password" class="form-label">Password</label>
            <input type="password" class="form-control" name="Password">
          </div>
            <div class="col-6 mb-3">
          <button type="submit" class="btn btn-success"value="Login">Login</button>
          </div>
         
         </form>
          <div class="col-6 mb-3">
              <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("RegistrationPage", "Registration")'">Register Customer</button>
          </div>
           <div class="col-6 mb-3">
              <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("AdminLogin", "Authentication")'">Go to Admin Login</button>
          </div>
          
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>